"""Transition facade for Streamlit assistant research helpers."""

from llm_tools.apps.streamlit_assistant.app import (  # pragma: no cover
    AssistantResearchSessionController,
    AssistantResearchSessionView,
    _append_research_summary,
    _apply_research_action_result,
    _build_research_controller,
    _build_research_session_view,
    _conditional_button,
    _launch_research_task,
    _payload_for_display,
    _research_issue_messages,
    _research_session_title,
    _research_summary_inserted,
    _research_summary_text,
    _research_verification_copy,
    _run_and_append_research_action,
    _run_research_action,
    _select_research_session,
    _selected_research_session_id,
    _updated_research_view,
)

__all__ = [  # pragma: no cover
    "AssistantResearchSessionController",
    "AssistantResearchSessionView",
    "_append_research_summary",
    "_apply_research_action_result",
    "_build_research_controller",
    "_build_research_session_view",
    "_conditional_button",
    "_launch_research_task",
    "_payload_for_display",
    "_research_issue_messages",
    "_research_session_title",
    "_research_summary_inserted",
    "_research_summary_text",
    "_research_verification_copy",
    "_run_and_append_research_action",
    "_run_research_action",
    "_select_research_session",
    "_selected_research_session_id",
    "_updated_research_view",
]
